name: build-xs-melodic

on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  xs-melodic:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: main, BUILDER: catkin_tools, NOT_TEST_BUILD: true}
          - {ROS_DISTRO: melodic, ROS_REPO: main, BUILDER: catkin_make, NOT_TEST_BUILD: true}
    runs-on: ubuntu-18.04
    env:
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
    steps:
      - name: Checkout ROS Toolboxes
        uses: actions/checkout@v3
      - name: Prepare Workspace
        run: |
          git clone https://github.com/Interbotix/interbotix_ros_core
          mkdir src
          mv interbotix_ros_core src
          mv interbotix_common_toolbox src && mv interbotix_xs_toolbox src && mv interbotix_perception_toolbox src
          cd src/interbotix_ros_core && git checkout devel && cd ../..
          rm src/interbotix_ros_core/interbotix_ros_xseries/CATKIN_IGNORE
          rm src/interbotix_common_toolbox/interbotix_moveit_interface/CATKIN_IGNORE
          rm src/interbotix_xs_toolbox/CATKIN_IGNORE
          rm src/interbotix_perception_toolbox/CATKIN_IGNORE
      - name: Get cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.ROS_DISTRO }}-${{ matrix.ROS_REPO }}-${{github.run_id}}
          restore-keys: |
            ccache-${{ matrix.ROS_DISTRO }}-${{ matrix.ROS_REPO }}-
      - name: ROS-I CI
        uses: ros-industrial/industrial_ci@master
        with:
          config: ${{toJSON(matrix.env)}}
