name: build-xs-noetic

on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel

defaults:
  run:
    shell: bash

jobs:
  xs-noetic:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic,  ROS_REPO: main}
          - {ROS_DISTRO: noetic,  ROS_REPO: main, BUILDER: catkin_make}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ROS Toolboxes
        uses: actions/checkout@v2
      - name: Prepare Workspace
        run: |
          git clone https://github.com/Interbotix/interbotix_ros_core
          mkdir src
          mv interbotix_ros_core src
          mv interbotix_common_toolbox src && mv interbotix_xs_toolbox src && mv interbotix_perception_toolbox src
          cd src/interbotix_ros_core && git checkout devel && cd ../..
          rm src/interbotix_ros_core/interbotix_ros_xseries/CATKIN_IGNORE
          rm src/interbotix_common_toolbox/interbotix_moveit_interface/CATKIN_IGNORE
          rm src/interbotix_xs_toolbox/CATKIN_IGNORE
          rm src/interbotix_perception_toolbox/CATKIN_IGNORE
      - name: ROS-I CI
        uses: ros-industrial/industrial_ci@master
        with:
          config: ${{toJSON(matrix.env)}}
